databases:
  - name: Baito_DB
    databaseName: baito_db
    user: baito
    region: singapore

services:
  - type: web
    name: baito
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Baito_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

